INSERT INTO FEATURE_REQUIREMENT (FEATURE_CODE, SOFT_HARD_CODE, SOFT_HARD_FLAG, PRESENT_NOTPRESENT_FLAG)
VALUES
 ('A', 'GdS6TI','S','P'),
 ('A', '93ZSw9','S','P'),
 ('A', 'btZUSp','S','P'),
 ('A', 'MZgsou','S','P'),
 ('A', 'Di75Ry','S','P'),
 ('A', '0vhcNa','S','P'),
 ('A', '33MHDf','S','P'),
--  ('A', 'Di75Ry','S','P'),
 ('A', 'L34Pur','S','P'),

 ('A', 'ykzkfK','S','N'),
 ('A', '87Zhwo','S','N'),
 ('A', 'y4XKWo','S','N'),
 ('A', 'ay0pW2','S','N'),
 ('A', '44OmDi','S','N'),
 ('A', 'aJsd3i','S','N'),
 ('A', 'Qoflqf','S','N'),
 ('A', '2EzZXE','S','N'),
 ('A', 'j3mmf8','S','N'),
 ('A', 'MUR8Lx','S','N'),
 ('A', 'E6GYk7','S','N'),
 ('A', 'rDJyQX','S','N'),

 ('A', 'rlTcbX','H','P'),
 ('A', 'wEEA00','H','P'),
 ('A', 'SoF5uL','H','P'),
 ('A', 'VhB9VY','H','P'),
 ('A', 'NWytcy','H','P'),

 ('A', 'yZDXJJ','H','N'),
 ('A', 'tMI8bI','H','N'),
 ('A', 'DS8tZU','H','N'),
 ('A', 'PgOtkv','H','N'),
 ('A', 'PuyTwj','H','N'),
 ('A', 'ObZw28','H','N'),
 ('A', 'ZCLFOe','H','N'),
 ('A', 'jyP5PK','H','N'),
 ('A', 'pS5ZQs','H','N'),
 ('A', 'rcjjPX','H','N'),
 ('A', '6VO6Uq','H','N'),
 ('A', 'DAlCk4','H','N'),
 ('A', 'YxKjcX','H','N');

INSERT INTO FEATURE_REQUIREMENT (FEATURE_CODE, SOFT_HARD_CODE, SOFT_HARD_FLAG, PRESENT_NOTPRESENT_FLAG)
VALUES
 ('B', 'FhFXVE','S','P'),
 ('B', 'FVlp0N','S','P'),
 ('B', 'I25pUg','S','P'),
 ('B', 'PeQWGL','S','P'),
 ('B', 'LYZzKL','S','P'),
 ('B', 'Cd9t6T','S','P'),
 ('B', 'pYgxjp','S','P'),
 ('B', 'T55Adn','S','P'),
 ('B', 'cjKv9N','S','P'),

 ('B', 'yfepdF','S','N'),
 ('B', 'Q54BVi','S','N'),
 ('B', '1QNx4P','S','N'),
 ('B', 'u9XCsm','S','N'),
 ('B', 'RgrAEU','S','N'),
 ('B', '0M97HZ','S','N'),
 ('B', 'BD80qR','S','N'),
 ('B', 'RGOkrt','S','N'),
 ('B', 'y4XKWo','S','N'),
 ('B', 'LV7Msr','S','N'),
 ('B', '0OEvxe','S','N'),
 ('B', 'VLyf6R','S','N'),
  ('B', 's1I5dm','S','N'),
 ('B', 'I4wRf9','S','N'),

 ('B', 'fMm4Hl','H','P'),
 ('B', 'PWO7oa','H','P'),
 ('B', 'F73iHn','H','P'),

 ('B', 'mrGqkV','H','N'),
 ('B', 'Ps19N7','H','N');

INSERT INTO FEATURE_REQUIREMENT (FEATURE_CODE, SOFT_HARD_CODE, SOFT_HARD_FLAG, PRESENT_NOTPRESENT_FLAG)
VALUES
 ('C', 'CtbvOZ','S','P'),
 ('C', 'bpdM7a','S','P'),
 ('C', 'rTM6gD','S','P'),
 ('C', 'LvXPPT','S','P'),
 ('C', 'Gwz57A','S','P'),
 ('C', 'NNTgVk','S','P'),
 ('C', 'dt5WJj','S','P'),
 ('C', 'zTUQwE','S','P'),
 ('C', 'ufX8mD','S','P'),
('C', '0vhcNa','S','P'),
 ('C', 'UPCZFv','S','P'),
 ('C', 'uUZjNJ','S','P'),
 ('C', 'ljnm95','S','P'),
 ('C', 'QP8Bls','S','P'),
 ('C', 'egNmFq','S','P'),
 --('C', 'Gwz57A','S','P'),
 ('C', 'PJyE8c','S','P'),
 ('C', 'pYgxjp','S','P'),

 ('C', 'T2WuvF','S','N'),

 ('C', 'wv2CZs','H','P'),
 ('C', 'CEuBzO','H','P'),
 ('C', 'Cu5fGc','H','P'),
  ('C', 'jvqI5i','H','P'),
 ('C', 'pZLSFn','H','P'),
 ('C', 'eUMxfa','H','P'),

 ('C', 'JY3Vcn','H','N'),
 ('C', '8PielJ','H','N'),
  ('C', 'NcOLyY','H','N'),
 ('C', 'Zfahrb','H','N'),
  ('C', 'iKALCh','H','N'),
 ('C', '6IHTbr','H','N');
